# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.3.0
      environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo
  working_directory: ~/repo

aliases:
  - &restore_cache
      keys:
        - v2-dependencies-{{ checksum "package.json" }}
        - v2-dependencies-
  - &save_cache
      paths:
        - node_modules
      key: v2-dependencies-{{ checksum "package.json" }}

jobs:
   - welcome/run
